############# English navigation ##############

# main menu
[[main]]
name = "Accueil"
url = "/"
weight = 1

[[main]]
name = "Articles"
url = "/articles"
weight = 2

# footer menu
[[footer]]
name = "Articles"
url = "/articles"
weight = 1

[[footer]]
name = "Liste des rapports"
url = "https://shop.immoyield.fr"
weight = 1

[[footer]]
name = "FAQ"
url = "/faq"
weight = 1